### ISSUE TITLE
Incluir limitaciones del brazo en MotionPlan::isArmProfileSafe()

### ISSUE THREAD

**Issue by JRicardoSan** [spaceuma/ADE-Mobile_Manipulation#122]
De esta manera se tienen en cuenta a la hora de comprobar que el perfil que se genera no contiene consignas de joints prohibidas por software. Habrá que comprobar que esto también se cumpla en los perfiles de las operaciones PICK, DROP y SWEEPING.

**Comment by gonzalopd96** [comment]
Cierro este issue de ADE como "Not planned" ya que no se le va a dar más soporte por ahora y el repo está público...
