### ISSUE TITLE
Crear funciones para configurar ciertos parámetros

### ISSUE THREAD

**Issue by JRicardoSan** [spaceuma/ADE-Mobile_Manipulation#64]
Variables: z_res, cost_gain, risk_distance, variables del waypoint navigation, ...
Debe ser un archivo externo que el componente pueda leer. De esta manera no hace falta compilar para hacer cambios en los valores de estas variables.

**Comment by gonzalopd96** [comment]
Cierro este issue de ADE como "Not planned" ya que no se le va a dar más soporte por ahora y el repo está público...

**Comment by gonzalopd96** [comment]
De hecho, se ha resuelto en CoRob-X...
